//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoncheToolkit.EffectsCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuTextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuTextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoncheToolkit.EffectsCreator.Resources.MenuTextResources", typeof(MenuTextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        internal static string File_Exit {
            get {
                return ResourceManager.GetString("File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        internal static string File_New {
            get {
                return ResourceManager.GetString("File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAs.
        /// </summary>
        internal static string File_SaveAs {
            get {
                return ResourceManager.GetString("File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        internal static string Import_Add {
            get {
                return ResourceManager.GetString("Import_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Component.
        /// </summary>
        internal static string Import_Add_Component {
            get {
                return ResourceManager.GetString("Import_Add_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Model.
        /// </summary>
        internal static string Import_Add_Model {
            get {
                return ResourceManager.GetString("Import_Add_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Primitive.
        /// </summary>
        internal static string Import_Add_Primitive {
            get {
                return ResourceManager.GetString("Import_Add_Primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube.
        /// </summary>
        internal static string Import_Add_Primitive_Cube {
            get {
                return ResourceManager.GetString("Import_Add_Primitive_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Import_Add_Primitive_Square {
            get {
                return ResourceManager.GetString("Import_Add_Primitive_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string Import_Add_Primitive_Triangle {
            get {
                return ResourceManager.GetString("Import_Add_Primitive_Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Shaders.
        /// </summary>
        internal static string Import_Shaders {
            get {
                return ResourceManager.GetString("Import_Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Template.
        /// </summary>
        internal static string Import_ShaderTemplate {
            get {
                return ResourceManager.GetString("Import_ShaderTemplate", resourceCulture);
            }
        }
    }
}
